export enum TOPICS {
  TRANSACTION_VALIDATION = 'TRANSACTION_VALIDATION',
  FRAUD_VALIDATION_RESPONSE = 'FRAUD_VALIDATION_RESPONSE',
}

export enum GROUP_IDS {
  FRAUD_VALIDATION_GROUP = 'FRAUD_VALIDATION_GROUP',
}
