export enum TransactionTypes {
    INTERNAL_TRANSACTION,
    EXTERNAL_TRANSACTION
}

export enum TransactionStatuses {
    PENDING = 'PENDING',
    COMPLETED = 'COMPLETED',
    REJECTED = 'REJECTED'
}

export enum Events {
    ON_TRANSACTION_CREATE = 'ON_TRANSACTION_CREATE',
    ON_TRANSACTION_COMPLETE = 'ON_TRANSACTION_COMPLETE',
    ON_TRANSACTION_REJECT = 'ON_TRANSACTION_REJECT'
}