services:
  Apps.controllers.CreateTransactionPostController:
    class: ../../../../../../controllers/transaction/create/CreateTransactionPostController
    arguments: ['@Transaction.Contexts.CreateTransaction']
