export const DATA_TIMESTAMP_DATE_FORMAT = 'YYYYMMDDHH:mm:ss';
export const DAILY_ROTATE_FILE_TIMESTAMP_FORMAT = 'YYYY-MM-DD';

export const ISO_8601_FORMAT_TIMESTAMP_NO_TIMEZONE = 'YYYY-MM-DD[T]HH:mm:ss.SSS';
export const ISO_8601_FORMAT_TIMESTAMP = 'YYYY-MM-DD[T]HH:mm:ss.SSS[Z]';
export const ISO_8601_FORMAT_DATE = 'YYYY-MM-DD';
export const ISO_8601_FORMAT_TIME = 'HH:mm:ss';
