GET http://192.168.208.6:3003/transactions

###
POST http://192.168.208.6:3003/transactions
Content-Type: application/json

{
  "accountExternalIdDebit": "Guid4",
  "tranferTypeId": 1,
  "value": 1080
}