FROM node:18-alpine as base

ARG app
ARG migrate
RUN npm install -g ts-node typescript
COPY ./${app} /opt/app
WORKDIR /opt/app
RUN npm install
RUN npm install --save-dev
EXPOSE  3000

CMD ["npm", "run", "migration:run"]