import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1681230996475 implements MigrationInterface {
    name = 'Init1681230996475'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "transaction_status" ("transactionStatusId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(20) NOT NULL, CONSTRAINT "PK_2454d9d5aa8140b1804f66e6702" PRIMARY KEY ("transactionStatusId"))`);
        await queryRunner.query(`CREATE TABLE "transaction_type" ("transactionTypeId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(20) NOT NULL, CONSTRAINT "PK_3e327c7548cfe033cf40fe843ee" PRIMARY KEY ("transactionTypeId"))`);
        await queryRunner.query(`CREATE TABLE "transaction" ("transactionExternalId" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountExternalIdDebit" uuid NOT NULL, "accountExternalIdCredit" uuid NOT NULL, "tranferTypeId" integer NOT NULL, "value" numeric NOT NULL, "createdAt" TIMESTAMP NOT NULL, "transactionTypeId" integer NOT NULL, "transactionStatusId" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_e9d33ad38b57ee3c0b6af71e061" PRIMARY KEY ("transactionExternalId"))`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_0e57c323890648df9aa92e57a34" FOREIGN KEY ("transactionTypeId") REFERENCES "transaction_type"("transactionTypeId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_acb226c33f2e9022e76d04ca1dc" FOREIGN KEY ("transactionStatusId") REFERENCES "transaction_status"("transactionStatusId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_acb226c33f2e9022e76d04ca1dc"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_0e57c323890648df9aa92e57a34"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TABLE "transaction_type"`);
        await queryRunner.query(`DROP TABLE "transaction_status"`);
    }

}
