export const ANTI_FRAUD_CONSUMER = 'ANTI_FRAUD_CONSUMER';
export const ANTI_FRAUD_SERVICE_NAME = 'ANTI_FRAUD_SERVICE';
export const MAIN_CONSUMER_GROUP = 'MAIN_CONSUMER';
export const MAIN_SERVICE_NAME = 'MAIN_SERVICE';

export enum EVENTS {
    ON_TRANSACTION_CREATED = 'ON_TRANSACTION_CREATED',
    ON_TRANSACTION_VALIDATED = 'ON_TRANSACTION_VALIDATED'
}