import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrate1710805051746 implements MigrationInterface {
    name = 'Migrate1710805051746'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "TransactionStatus" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "code" smallint NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_33e635ce101797238893cc98015" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "TransactionType" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_931377e85eca50f80534a6305a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Transaction" ("transactionExternalId" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountExternalIdDebit" uuid NOT NULL, "accountExternalIdCredit" uuid NOT NULL, "value" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "TransactionStatus" uuid, "TransactionType" integer, CONSTRAINT "PK_33330ca5a43b5c144b7056c1960" PRIMARY KEY ("transactionExternalId"))`);
        await queryRunner.query(`ALTER TABLE "Transaction" ADD CONSTRAINT "FK_70047cc45c1be226294b32d11b0" FOREIGN KEY ("TransactionStatus") REFERENCES "TransactionStatus"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Transaction" ADD CONSTRAINT "FK_c282813945d44905cfe87b9eb40" FOREIGN KEY ("TransactionType") REFERENCES "TransactionType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Transaction" DROP CONSTRAINT "FK_c282813945d44905cfe87b9eb40"`);
        await queryRunner.query(`ALTER TABLE "Transaction" DROP CONSTRAINT "FK_70047cc45c1be226294b32d11b0"`);
        await queryRunner.query(`DROP TABLE "Transaction"`);
        await queryRunner.query(`DROP TABLE "TransactionType"`);
        await queryRunner.query(`DROP TABLE "TransactionStatus"`);
    }

}
