export const TRANSACTION_PENDING = 1;
export const TRANSACTION_APPROVED = 2;
export const TRANSACTION_REJECTED = 3;

export const TRANSACTION_PENDING_NAME = 'PENDING';
export const TRANSACTION_APPROVED_NAME = 'APPROVED';
export const TRANSACTION_REJECTED_NAME = 'REJECTED';

export const TRANSACTION_CREDIT_TYPE = 'CREDIT';
export const TRANSACTION_DEBIT_TYPE = 'DEBIT';
