FROM node:16-alpine

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

WORKDIR /code

COPY package*.json ./
COPY ./build ./build
COPY ./.env ./.env


RUN npm install

COPY . .

CMD [ "node", "build/index.js" ] 