### Create transaction
POST http://localhost:3000/transaction
Content-Type: application/json

{
  "accountExternalIdDebit": "134-1234-1234-1234",
  "accountExternalIdCredit": "1230123-423-52-312",
  "transferTypeId": 1,
  "value": 1200
}

### Get Transaction
POST http://localhost:3000/transaction/get
Content-Type: application/json

{
  "transactionType": {
    "name": "TX_WIRE_TRANSFER"
  },
  "transactionStatus": {
    "name": "REJECTED"
  },
  "value": 1200,
  "createdAt": "2023-08-01T19:47:09.604Z"
}
