export const TRANSACTION_STATUSES_3 = {
  APRROVED: 'APPROVED',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
};
export enum TRANSACTION_STATUSES {
  'APROVED',
  'PENDING',
  'REJECTED',
}

export enum TRANSACTION_STATUSES_2 {
  'APROVED' = 'APRROVED',
  'PENDING' = 'PENDING',
  'REJECTED' = 'REJECTED',
}

export type ITRANSACTION_STATUSES = 'APRROVED' | 'PENDING' | 'REJECTED';
