export enum ConfigurationEnum {
  ENV = 'ENV',

  APP_PORT = 'APP_PORT',
  APP_HOST = 'APP_HOST',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',

  BROKER_SERVER='BROKER_SERVER',
  BROKER_USERNAME='BROKER_USERNAME',
  BROKER_PASSWORD='BROKER_PASSWORD',
  BROKER_CONSUMER='BROKER_CONSUMER',
  TOPIC_MESSAGE='TOPIC_MESSAGE',
  TOPIC_RECEIPT='TOPIC_RECEIPT',

  API_URL='API_URL'

}
