
export enum TransactionTypeEnum {
  BANK_TRANSFERS = 1,
  DEBIT_OR_CREDIT_CARD_PURCHASES = 2,
  LOANS = 3,
  BILL_PAYMENTS = 4,
  SALARY_AND_PAYROLL_PAYMENTS = 5,
  REFUNDS = 6,
  INTERNAL_TRANSFERS = 7,
  INVESTMENTS_AND_WITHDRAWALS = 8,
  TAX_PAYMENTS = 9,
  REFUNDS_AND_CANCELLATIONS = 10,
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
