export enum TransactionPattern {
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  LIST_TRANSACTION = 'LIST_TRANSACTION',
  FIND_ONE_TRANSACTION = 'FIND_ONE_TRANSACTION',
  APPROVED_TRANSACTION = 'APPROVED_TRANSACTION',
  REJECTED_TRANSACTION = 'REJECTED_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  VALIDATE_TRANSACTION = 'VALIDATE_ANTIFRAUD',
}
