export const TYPEORM_OPTIONS = 'TYPEORM_OPTIONS';
export const KAFKA_OPTIONS = 'KAFKA_OPTIONS';
export const GRAPHQL_OPTIONS = 'GRAPHQL_OPTIONS';
export const TRANSACTION_SERVICE = 'TRANSACTION_SERVICE';
export const VALIDATE_TRANSACTION = 'VALIDATE_TRANSACTION'
export const TRANSACTION_VALIDATED = 'TRANSACTION_VALIDATED'