export const TRANSACTION_CONSUMER = 'TRANSACTION_CONSUMER';
export const ANTI_FRAUD_CONSUMER = 'ANTI_FRAUD_CONSUMER';

export enum EVENTS {
    ON_TRANSACTION_CREATED = 'ON_TRANSACTION_CREATED',
    ON_TRANSACTION_VALIDATED = 'ON_TRANSACTION_VALIDATED'
}