export const ANTI_FRAUD_SERVER = 'ANTI_FRAUD_SERVER';
export const ANTI_FRAUD_CONSUMER_SERVER = 'ANTI_FRAUD_CONSUMER_SERVER';
export const TRANSACTION_SERVER = 'TRANSACTION_SERVER';
export const TRANSACTION_CONSUMER_CLIENT = 'TRANSACTION_CONSUMER_CLIENT';
export const SESSION_TIMEOUT = 30000;
export const RETRY = 30;
export const IS_VALID_TRANSACTION_MESSAGE_PATTERN = 'is_valid_transaction';
export const CHANGE_STATUS_TRANSACTION_MESSAGE_PATTERN =
  'change_status_transaction';
