export enum NotificationTopic {
    WHEN_IT_IS_CREATED_AN_TRANSACTION = "TRANSACTION_CREATED",
    WHEN_IT_IS_APPROVED_AN_TRANSACTION = "TRANSACTION_APPROVED",
    WHEN_IT_IS_REJECTED_AN_TRANSACTION = "TRANSACTION_REJECTED",
}